export const PREMIER_LEAGUE_TEAMS = [
  { id: 1, name: 'Arsenal', shortName: 'ARS', league: 'Premier League', primaryColor: '#EF0107', secondaryColor: '#FFFFFF', rating: 85 },
  { id: 2, name: 'Aston Villa', shortName: 'AVL', league: 'Premier League', primaryColor: '#670E36', secondaryColor: '#95BFE5', rating: 78 },
  { id: 3, name: 'Bournemouth', shortName: 'BOU', league: 'Premier League', primaryColor: '#DA291C', secondaryColor: '#000000', rating: 72 },
  { id: 4, name: 'Brentford', shortName: 'BRE', league: 'Premier League', primaryColor: '#E30613', secondaryColor: '#FFFFFF', rating: 74 },
  { id: 5, name: 'Brighton', shortName: 'BHA', league: 'Premier League', primaryColor: '#0057B8', secondaryColor: '#FFFFFF', rating: 76 },
  { id: 6, name: 'Chelsea', shortName: 'CHE', league: 'Premier League', primaryColor: '#034694', secondaryColor: '#FFFFFF', rating: 82 },
  { id: 7, name: 'Crystal Palace', shortName: 'CRY', league: 'Premier League', primaryColor: '#C4122E', secondaryColor: '#0055A5', rating: 73 },
  { id: 8, name: 'Everton', shortName: 'EVE', league: 'Premier League', primaryColor: '#003399', secondaryColor: '#FFFFFF', rating: 70 },
  { id: 9, name: 'Fulham', shortName: 'FUL', league: 'Premier League', primaryColor: '#FFFFFF', secondaryColor: '#000000', rating: 74 },
  { id: 10, name: 'Ipswich', shortName: 'IPS', league: 'Premier League', primaryColor: '#0044AA', secondaryColor: '#FFFFFF', rating: 68 },
  { id: 11, name: 'Leicester', shortName: 'LEI', league: 'Premier League', primaryColor: '#003090', secondaryColor: '#FDBE11', rating: 71 },
  { id: 12, name: 'Liverpool', shortName: 'LIV', league: 'Premier League', primaryColor: '#C8102E', secondaryColor: '#FFFFFF', rating: 88 },
  { id: 13, name: 'Man City', shortName: 'MCI', league: 'Premier League', primaryColor: '#6CABDD', secondaryColor: '#FFFFFF', rating: 90 },
  { id: 14, name: 'Man United', shortName: 'MUN', league: 'Premier League', primaryColor: '#DA291C', secondaryColor: '#FFFFFF', rating: 80 },
  { id: 15, name: 'Newcastle', shortName: 'NEW', league: 'Premier League', primaryColor: '#241F20', secondaryColor: '#FFFFFF', rating: 82 },
  { id: 16, name: 'Nottm Forest', shortName: 'NFO', league: 'Premier League', primaryColor: '#DD0000', secondaryColor: '#FFFFFF', rating: 74 },
  { id: 17, name: 'Southampton', shortName: 'SOU', league: 'Premier League', primaryColor: '#D71920', secondaryColor: '#FFFFFF', rating: 65 },
  { id: 18, name: 'Spurs', shortName: 'TOT', league: 'Premier League', primaryColor: '#FFFFFF', secondaryColor: '#132257', rating: 79 },
  { id: 19, name: 'West Ham', shortName: 'WHU', league: 'Premier League', primaryColor: '#7A263A', secondaryColor: '#1BB1E7', rating: 76 },
  { id: 20, name: 'Wolves', shortName: 'WOL', league: 'Premier League', primaryColor: '#FDB913', secondaryColor: '#231F20', rating: 72 },
];

export const CHAMPIONSHIP_TEAMS = [
  { id: 21, name: 'Leeds United', shortName: 'LEE', league: 'Championship', primaryColor: '#FFFFFF', secondaryColor: '#1D428A', rating: 74 },
  { id: 22, name: 'Sheffield Utd', shortName: 'SHU', league: 'Championship', primaryColor: '#EE2737', secondaryColor: '#000000', rating: 72 },
  { id: 23, name: 'Sunderland', shortName: 'SUN', league: 'Championship', primaryColor: '#EB172B', secondaryColor: '#FFFFFF', rating: 70 },
  { id: 24, name: 'Burnley', shortName: 'BUR', league: 'Championship', primaryColor: '#6C1D45', secondaryColor: '#99D6EA', rating: 71 },
  { id: 25, name: 'Middlesbrough', shortName: 'MID', league: 'Championship', primaryColor: '#EE3124', secondaryColor: '#FFFFFF', rating: 70 },
  { id: 26, name: 'Norwich City', shortName: 'NOR', league: 'Championship', primaryColor: '#00A650', secondaryColor: '#FFF200', rating: 69 },
  { id: 27, name: 'Preston NE', shortName: 'PNE', league: 'Championship', primaryColor: '#FFFFFF', secondaryColor: '#004B9B', rating: 66 },
  { id: 28, name: 'Millwall', shortName: 'MIL', league: 'Championship', primaryColor: '#001D5E', secondaryColor: '#FFFFFF', rating: 67 },
  { id: 29, name: 'Coventry City', shortName: 'COV', league: 'Championship', primaryColor: '#1B6EC2', secondaryColor: '#FFFFFF', rating: 68 },
  { id: 30, name: 'Hull City', shortName: 'HUL', league: 'Championship', primaryColor: '#F18A00', secondaryColor: '#000000', rating: 67 },
  { id: 31, name: 'Watford', shortName: 'WAT', league: 'Championship', primaryColor: '#FBEE23', secondaryColor: '#ED2127', rating: 69 },
  { id: 32, name: 'West Brom', shortName: 'WBA', league: 'Championship', primaryColor: '#122F67', secondaryColor: '#FFFFFF', rating: 70 },
  { id: 33, name: 'Cardiff City', shortName: 'CAR', league: 'Championship', primaryColor: '#0070B5', secondaryColor: '#FFFFFF', rating: 66 },
  { id: 34, name: 'Stoke City', shortName: 'STK', league: 'Championship', primaryColor: '#E03A3E', secondaryColor: '#FFFFFF', rating: 67 },
  { id: 35, name: 'QPR', shortName: 'QPR', league: 'Championship', primaryColor: '#1D5BA4', secondaryColor: '#FFFFFF', rating: 66 },
  { id: 36, name: 'Blackburn', shortName: 'BLK', league: 'Championship', primaryColor: '#009EE0', secondaryColor: '#FFFFFF', rating: 68 },
  { id: 37, name: 'Derby County', shortName: 'DER', league: 'Championship', primaryColor: '#FFFFFF', secondaryColor: '#000000', rating: 65 },
  { id: 38, name: 'Plymouth', shortName: 'PLY', league: 'Championship', primaryColor: '#007B5E', secondaryColor: '#FFFFFF', rating: 64 },
  { id: 39, name: 'Swansea City', shortName: 'SWA', league: 'Championship', primaryColor: '#FFFFFF', secondaryColor: '#000000', rating: 66 },
  { id: 40, name: 'Bristol City', shortName: 'BRS', league: 'Championship', primaryColor: '#E3000B', secondaryColor: '#FFFFFF', rating: 65 },
  { id: 41, name: 'Sheffield Wed', shortName: 'SHW', league: 'Championship', primaryColor: '#003893', secondaryColor: '#FFFFFF', rating: 66 },
  { id: 42, name: 'Oxford Utd', shortName: 'OXF', league: 'Championship', primaryColor: '#FFD200', secondaryColor: '#000000', rating: 62 },
  { id: 43, name: 'Luton Town', shortName: 'LUT', league: 'Championship', primaryColor: '#F78F1E', secondaryColor: '#FFFFFF', rating: 67 },
  { id: 44, name: 'Portsmouth', shortName: 'POM', league: 'Championship', primaryColor: '#003087', secondaryColor: '#FFFFFF', rating: 65 },
];

export const ALL_TEAMS = [...PREMIER_LEAGUE_TEAMS, ...CHAMPIONSHIP_TEAMS];
